
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cms_mssp_connector'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
  input_database: tuva
  input_schema: raw_data

  demo_data_only: false
  claims_enabled: true
  cms_alr_connector: true
  provider_attribution_enabled: true

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
   cms_mssp_connector:
     final:
       +materialized: table
     intermediate:
       +materialized: table
     staging:
       +materialized: view
