select
    cast(CUR_CLM_UNIQ_ID                    as {{ dbt.type_string() }})  as CUR_CLM_UNIQ_ID,
    cast(CLM_LINE_NUM                       as integer)                   as CLM_LINE_NUM,
    cast(BENE_MBI_ID                        as {{ dbt.type_string() }})  as BENE_MBI_ID,
    cast(BENE_HIC_NUM                       as {{ dbt.type_string() }})  as BENE_HIC_NUM,
    cast(CLM_TYPE_CD                        as {{ dbt.type_string() }})  as CLM_TYPE_CD,
    cast(CLM_NGACO_PBPMT_SW                 as {{ dbt.type_string() }})  as CLM_NGACO_PBPMT_SW,
    cast(CLM_NGACO_PDSCHRG_HCBS_SW          as {{ dbt.type_string() }})  as CLM_NGACO_PDSCHRG_HCBS_SW,
    cast(CLM_NGACO_SNF_WVR_SW               as {{ dbt.type_string() }})  as CLM_NGACO_SNF_WVR_SW,
    cast(CLM_NGACO_TLHLTH_SW                as {{ dbt.type_string() }})  as CLM_NGACO_TLHLTH_SW,
    cast(CLM_NGACO_CPTATN_SW                as {{ dbt.type_string() }})  as CLM_NGACO_CPTATN_SW,
    cast(CLM_DEMO_1ST_NUM                   as {{ dbt.type_string() }})  as CLM_DEMO_1ST_NUM,
    cast(CLM_DEMO_2ND_NUM                   as {{ dbt.type_string() }})  as CLM_DEMO_2ND_NUM,
    cast(CLM_DEMO_3RD_NUM                   as {{ dbt.type_string() }})  as CLM_DEMO_3RD_NUM,
    cast(CLM_DEMO_4TH_NUM                   as {{ dbt.type_string() }})  as CLM_DEMO_4TH_NUM,
    cast(CLM_DEMO_5TH_NUM                   as {{ dbt.type_string() }})  as CLM_DEMO_5TH_NUM,
    {{ cast_numeric('CLM_PBP_INCLSN_AMT') }}                             as CLM_PBP_INCLSN_AMT,
    {{ cast_numeric('CLM_PBP_RDCTN_AMT') }}                              as CLM_PBP_RDCTN_AMT,
    cast(CLM_NGACO_CMG_WVR_SW               as {{ dbt.type_string() }})  as CLM_NGACO_CMG_WVR_SW,
    {{ cast_numeric('CLM_INSTNL_PER_DIEM_AMT') }}                        as CLM_INSTNL_PER_DIEM_AMT,
    {{ cast_numeric('CLM_MDCR_IP_BENE_DDCTBL_AMT') }}                    as CLM_MDCR_IP_BENE_DDCTBL_AMT,
    {{ cast_numeric('CLM_MDCR_COINSRNC_AMT') }}                          as CLM_MDCR_COINSRNC_AMT,
    {{ cast_numeric('CLM_BLOOD_LBLTY_AMT') }}                            as CLM_BLOOD_LBLTY_AMT,
    {{ cast_numeric('CLM_INSTNL_PRFNL_AMT') }}                           as CLM_INSTNL_PRFNL_AMT,
    {{ cast_numeric('CLM_NCVRD_CHRG_AMT') }}                             as CLM_NCVRD_CHRG_AMT,
    {{ cast_numeric('CLM_MDCR_DDCTBL_AMT') }}                            as CLM_MDCR_DDCTBL_AMT,
    cast(CLM_RLT_COND_CD                    as {{ dbt.type_string() }})  as CLM_RLT_COND_CD,
    {{ cast_numeric('CLM_OPRTNL_OUTLR_AMT') }}                           as CLM_OPRTNL_OUTLR_AMT,
    {{ cast_numeric('CLM_MDCR_NEW_TECH_AMT') }}                          as CLM_MDCR_NEW_TECH_AMT,
    {{ cast_numeric('CLM_ISLET_ISOLN_AMT') }}                            as CLM_ISLET_ISOLN_AMT,
    {{ cast_numeric('CLM_SQSTRTN_RDCTN_AMT') }}                          as CLM_SQSTRTN_RDCTN_AMT,
    cast(CLM_1_REV_CNTR_ANSI_RSN_CD         as {{ dbt.type_string() }})  as CLM_1_REV_CNTR_ANSI_RSN_CD,
    cast(CLM_1_REV_CNTR_ANSI_GRP_CD         as {{ dbt.type_string() }})  as CLM_1_REV_CNTR_ANSI_GRP_CD,
    {{ cast_numeric('CLM_MIPS_PMT_AMT') }}                               as CLM_MIPS_PMT_AMT,
    cast(FILE_PATH                          as {{ dbt.type_string() }})  as FILE_PATH,
    cast(DIRECTORY_NAME                     as {{ dbt.type_string() }})  as DIRECTORY_NAME,
    cast(FILE_NAME                          as {{ dbt.type_string() }})  as FILE_NAME,
    {{ try_to_cast_date('FILE_DATE') }}                                   as FILE_DATE
from {{ source('mssp_raw', 'cclfb_claims_benefit_enhancement_and_demonstration_code_file_cclfb') }}
